- name: Add universe repository for bionic
  apt_repository:
    repo: deb http://archive.ubuntu.com/ubuntu bionic universe
    state: present

- name: Install Ruby dependencies
  apt:
    name: ['git','git-core', 'curl', 'dirmngr', 'gnupg', 'apt-transport-https',
      'ca-certificates', 'redis-server', 'redis-tools', 'gcc', 'autoconf',
      'bison', 'nodejs', 'yarn', 'checkinstall', 'python3-psycopg2',
      'build-essential', 'zlib1g-dev', 'openssl', 'libssl-dev', 'libyaml-dev',
      'libreadline-dev', 'libreadline6-dev', 'libxml2-dev', 'libffi-dev',
      'libncurses5-dev', 'libxslt1-dev', 'libcurl4-openssl-dev',
      'software-properties-common', 'libgdbm6', 'libgdbm-dev', 'libdb-dev',
      'libffi-dev', 'zlib1g-dev', 'postgresql', 'postgresql-contrib',
      'libjemalloc-dev', 'software-properties-common', 'libpq-dev', 'gnupg',
      'gnupg2', 'certbot', 'python-certbot-nginx']
    update_cache: yes

- name: Create rails user and grant privs
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: ansible_rails
    password: "{{ db_password[0] }}"
    role_attr_flags: CREATEDB,SUPERUSER
