- name: Install Ruby dependencies
  apt:
    name: ['git-core', 'gcc', 'autoconf', 'bison', 'build-essential', 'checkinstall', 'zlib1g-dev', 'openssl', 'libssl-dev', 'libyaml-dev', 'libreadline-dev', 'libreadline6-dev', 'libxml2-dev', 'libffi-dev', 'libncurses5-dev', 'libxslt1-dev', 'libcurl4-openssl-dev', 'software-properties-common', 'libffi-dev', 'zlib1g-dev', 'postgresql', 'postgresql-contrib', 'nodejs', 'yarn', 'libjemalloc-dev', 'software-properties-common', 'libpq-dev']

- name: Create rails user and grant privs
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: ansible_rails
    password: db_password
    role_attr_flags: CREATEDB,NOSUPERUSER

- name: Download ruby-install
  become: no
  get_url:
    url: https://github.com/postmodern/ruby-install/archive/v0.8.1.tar.gz
    dest: /home/deploy/ruby-install-0.8.1.tar.gz

- name: Extract ruby-install tarball
  unarchive:
    src: /home/deploy/ruby-install-0.8.1.tar.gz
    dest: /home/deploy
    creates: /home/deploy/ruby-install-0.8.1
    remote_src: yes

- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
    creates=/home/deploy/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install 15.5.0 && nvm alias default 15.5.0"
    creates=/home/deploy/.nvm/alias

- name: Install YVM
  args:
    warn: false
  shell: |
    curl -s https://raw.githubusercontent.com/tophat/yvm/master/scripts/install.js | node

- name: Install yarn 1.22.10
  shell: |
    /bin/bash -c "source ~/.yvm/yvm.sh && yvm install 1.22.10 && yvm alias default 1.22.10"