- name: Add deploy user
  user:
    name: deploy
    shell: /bin/bash

- name: Permission setup for deploy user
  become_user: root
  # chmod 700: owner can read, write, execute
  command: chmod 700 /home/deploy/.ssh

- name: Setup shell for deploy user
  command: usermod -s /bin/bash deploy

- name: Setup authorized_keys only for deploy user
  # chmod 400: owner can read, write, execute
  command: chmod 400 /home/deploy/.ssh/authorized_keys

- name: Setup home only for deploy user
  # chmod 400: owner can read, write, execute
  command: chown deploy:deploy /home/deploy -R

- name: Setup sudo group for deploy user
  # chmod 400: owner can read, write, execute
  command: usermod -aG sudo deploy

- name: Add SSH key to server for deploy user
  authorized_key:
    user: deploy
    key: "{{ lookup('file', '/Users/yb_widyokarsono/.ssh/id_ed25519_yosefbennywidyo_deploy.pub') }}"