- name: Add deploy user
  user:
    name: deploy
    shell: /bin/bash

- name: Recursively change ownership of "/home/deploy" directory
  ansible.builtin.file:
    path: /home/deploy/
    state: directory
    mode: '700'
    recurse: yes
    owner: deploy
    group: root

- name: Setup home only for deploy user
  # chmod 400: owner can read, write, execute
  command: chown deploy:deploy /home/deploy -R
  args:
    warn: false

- name: Setup sudo group for deploy user
  # chmod 400: owner can read, write, execute
  command: usermod -aG sudo deploy

- name: Add SSH key to server for deploy user
  authorized_key:
    user: deploy
    key: "{{ lookup('file', '/Users/yb_widyokarsono/.ssh/id_ed25519.pub') }}"
